### ISSUE TITLE
"Empty List" issue

### ISSUE THREAD

**Issue by haswelldev** [hseeberger/akka-log4j#53]
when i'm trying to run an app this issue occurs: 

```
[ERROR] [07/29/2017 10:38:46.509] [system-akka.actor.default-dispatcher-2] [akka://system/system/log1-Log4jLogger] head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [07/29/2017 10:38:46.524] [system-akka.actor.default-dispatcher-2] [akka://system/system/log1-Log4jLogger] changing Recreate into Create after java.util.NoSuchElementException: head of empty list
[ERROR] [SECURITY][07/29/2017 10:38:46.872] [system-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(system)] Uncaught error from thread [system-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
Uncaught error from thread [system-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[system]
java.lang.NoSuchMethodError: akka.actor.Actor.$init$(Lakka/actor/Actor;)V
	at de.heikoseeberger.akkalog4j.Log4jLogger.<init>(Log4jLogger.scala:61)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at akka.util.Reflect$.instantiate(Reflect.scala:44)
	at akka.actor.NoArgsReflectConstructor.produce(IndirectActorProducer.scala:105)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:130)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:374)
	at akka.actor.dungeon.FaultHandling$class.faultRecreate(FaultHandling.scala:59)
	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:374)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:464)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

there is a simple project affected by this issue
https://github.com/sshaddicts/neuralswarm/tree/issue-with-log4j2

[pom.xml](https://github.com/sshaddicts/neuralswarm/blob/issue-with-log4j2/pom.xml)
[application.conf](https://github.com/sshaddicts/neuralswarm/blob/issue-with-log4j2/src/main/resources/application.conf)
[log4j2.xml](https://github.com/sshaddicts/neuralswarm/blob/issue-with-log4j2/src/main/resources/log4j2.xml)

**Comment by hseeberger** [comment]
You are using Akka for Scala 2.11, but Akka Log4j for Scala 2.12: that doesn't work.
